"""
Minimal RTF -> plain text converter.

The "*.doc" files downloaded from 국가법령정보센터 (law.go.kr) are really RTF files
generated by iText. They contain Korean text as \\uNNNN escapes, tables (\\cell/\\row)
and embedded images (\\binN / \\pict). Generic converters often break on the binary
image data, so this small parser handles exactly what those files use.
"""
from __future__ import annotations

import re
from pathlib import Path

# Groups whose content is never visible text
_SKIP_DESTINATIONS = {
    "fonttbl", "colortbl", "stylesheet", "info", "pict", "shppict", "nonshppict",
    "header", "footer", "headerl", "headerr", "headerf", "footerl", "footerr", "footerf",
    "listtable", "listoverridetable", "generator", "object", "themedata", "datastore",
    "latentstyles", "rsidtbl", "xmlnstbl", "mmathPr", "pgdsctbl",
}

_CONTROL_RE = re.compile(rb"\\([a-zA-Z]+)(-?\d+)? ?|\\'([0-9a-fA-F]{2})|\\(.)", re.S)


def rtf_to_text(data: bytes, codepage: str = "cp949") -> str:
    out: list[str] = []
    stack: list[tuple[bool, int]] = []   # (skip, uc) saved per group
    skip = False
    uc = 1              # number of fallback chars to skip after \uN
    pending_skip = 0    # fallback chars still to skip
    ansi_buf = bytearray()

    def flush_ansi() -> None:
        if ansi_buf:
            out.append(ansi_buf.decode(codepage, errors="ignore"))
            ansi_buf.clear()

    i, n = 0, len(data)
    while i < n:
        ch = data[i]
        if ch == 0x7B:  # {
            flush_ansi()
            stack.append((skip, uc))
            i += 1
            # "{\*\dest" -> ignorable destination
            if data.startswith(b"\\*", i):
                skip = True
            continue
        if ch == 0x7D:  # }
            flush_ansi()
            skip, uc = stack.pop() if stack else (False, 1)
            pending_skip = 0
            i += 1
            continue
        if ch == 0x5C:  # backslash
            m = _CONTROL_RE.match(data, i)
            if not m:
                i += 1
                continue
            i = m.end()
            word, arg, hexv, sym = m.group(1), m.group(2), m.group(3), m.group(4)

            if hexv is not None:
                if pending_skip:
                    pending_skip -= 1
                elif not skip:
                    ansi_buf.append(int(hexv, 16))
                continue
            if sym is not None:
                if sym in (b"\\", b"{", b"}") and not skip:
                    flush_ansi()
                    out.append(sym.decode())
                elif sym == b"~" and not skip:
                    out.append(" ")
                elif sym in (b"\n", b"\r") and not skip:
                    out.append("\n")
                continue

            w = word.decode()
            if w == "bin":  # raw binary block: skip N bytes
                i += int(arg or 0)
                continue
            if w in _SKIP_DESTINATIONS:
                skip = True
                continue
            if skip:
                continue
            flush_ansi()
            if w == "u":
                code = int(arg)
                if code < 0:
                    code += 65536
                out.append(chr(code))
                pending_skip = uc
            elif w == "uc":
                uc = int(arg or 1)
            elif w in ("par", "line", "row", "sect", "page"):
                out.append("\n")
            elif w == "cell":
                out.append(" | ")
            elif w == "tab":
                out.append("\t")
            elif w in ("emdash",):
                out.append("—")
            elif w in ("endash",):
                out.append("–")
            elif w in ("lquote", "rquote"):
                out.append("'")
            elif w in ("ldblquote", "rdblquote"):
                out.append('"')
            elif w == "bullet":
                out.append("•")
            continue

        # plain character
        if ch in (0x0D, 0x0A):
            i += 1
            continue
        if pending_skip:
            pending_skip -= 1
        elif not skip:
            ansi_buf.append(ch)
        i += 1

    flush_ansi()
    text = "".join(out)
    text = text.replace("\u00a0", " ").replace("\u3000", " ")
    # tidy up whitespace but keep line structure
    lines = [re.sub(r"[ \t]+", " ", ln).strip() for ln in text.split("\n")]
    return "\n".join(lines)


def read_rtf(path: str | Path) -> str:
    return rtf_to_text(Path(path).read_bytes())
